project:
  type: book
  post-render:
    - scripts/fix_links.py
    - scripts/fix_search_highlight.py

date-format: "MMMM D, YYYY"

book:
  title: "Evangel Presbytery Book of Church Order"
  subtitle: "Amended June 5, 2025"
  repo-url: https://github.com/Evangel-Presbytery/evangel-bco
  chapters:
    - index.qmd
    - 02-Form-of-Government.qmd
    - 03-The-Rules-of-Discipline.qmd
    - 04-Directory-for-the-Worship-of-God.qmd
    - 05-Appendix1-Presbytery-Forms.qmd
    - 06-Appendix2-Original-Texts-of-Liturgical-Forms.qmd
    - 07-Updates.qmd
  sidebar:
    header: TOCheader.qmd
    search: true
  favicon: "evangel-favicon-196.png"
  navbar: 
    title: false
    logo: logo-white.png
    logo-href: https://evangelpresbytery.com
    search: false
    left:
      - text: Book of Church Order
        href: https://bco.evangelpresbytery.com
      - text: Doctrinal Declarations
        href: https://ddp.evangelpresbytery.com
      - text: Bylaws
        href: https://bylaws.evangelpresbytery.com

format:
  html:
    number-sections: true
    css:
      - evangel-docs-global.css
      - bco.css
    toc-location: left
    include-in-header: in_header.html
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    toc: true
    toc-title: Table of Contents
    toc-depth: 2
    number-sections: false
    include-in-header:
      - evangel-docs-global.tex
      - bco.tex
